version: "3"

services:
  wuhanpl:
    container_name: wuhanpl
    image: wuhanpl:1.6
    environment:
      OUTPUT_FOLDER: '/outputs/'
      TZ: 'Europe/Warsaw'
    env_file:
      - .env
    volumes:
      - './outputs/:/outputs/'
    restart: unless-stopped
